### ISSUE TITLE
assert.yml issues 

### ISSUE THREAD

**Issue by szilard9554** [robertdebock/ansible-role-storage#2]
Hi 

First of all, thank you for the great role but using Ansible 2.14.1 I found the next issues:
1. task "Test if storage_mounts.dump is set correctly" checks if item.dump is boolean but it's a number 
2. task "Test if storage_mounts.mode is set correctly" checks if item.mode is number and if is > 0 - but the mode "0755" is string and also >0 makes no help on a string 

To mitigate the issues I made the next changes:
```diff 
diff --git a/tasks/assert.yml b/tasks/assert.yml
index a04ce8b..fcf64b7 100644
--- a/tasks/assert.yml
+++ b/tasks/assert.yml
@@ -235,8 +235,7 @@
   ansible.builtin.assert:
     that:
       - item.mode is defined
-      - item.mode is number
-      - item.mode > 0
+      - item.mode is string
     quiet: yes
   loop: "{{ storage_mounts }}"
   loop_control:
@@ -272,7 +271,7 @@
   ansible.builtin.assert:
     that:
       - item.dump is defined
-      - item.dump is boolean
+      - item.dump is number
       - item.dump in [0, 1]
     quiet: yes
   loop: "{{ storage_mounts }}"
   
```

**Comment by epou** [comment]
@robertdebock  would you mind creating a new release including this fix?

**Comment by robertdebock** [comment]
Yes, thanks for the reminder.
